# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starID', models.CharField(max_length=140)),
                ('started', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(default='123@123.com', max_length=254)),
            ],
        ),
    ]
