# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='account.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='follower_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='account.User'),
        ),
    ]
