# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170425_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_user',
            field=models.ManyToManyField(related_name='follower', to='account.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follower_user',
            field=models.ManyToManyField(related_name='follow', to='account.User'),
        ),
    ]
