# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=140)),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('up_num', models.IntegerField()),
                ('CID', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('date', models.DateField(auto_now_add=True)),
                ('up_num', models.IntegerField(default=0)),
                ('UID', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='UP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.CharField(max_length=140)),
                ('UID', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
