# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='CID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app.Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='up_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='account.User'),
        ),
    ]
