# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170423_2307'),
        ('app', '0002_auto_20170423_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='UP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_co', to='account.User'),
        ),
        migrations.AddField(
            model_name='content',
            name='UP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uop_cer', to='account.User'),
        ),
    ]
