# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170424_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UP',
        ),
    ]
