# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170423_2307'),
        ('app', '0004_delete_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='UP',
        ),
        migrations.AddField(
            model_name='content',
            name='UP',
            field=models.ManyToManyField(null=True, to='account.User'),
        ),
    ]
