# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170425_1549'),
        ('app', '0005_auto_20170425_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='UP',
        ),
        migrations.AddField(
            model_name='comment',
            name='UP',
            field=models.ManyToManyField(related_name='com_up', to='account.User'),
        ),
        migrations.AlterField(
            model_name='content',
            name='UP',
            field=models.ManyToManyField(related_name='con_up', to='account.User'),
        ),
    ]
